/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 src/assets/emblem3d.gltf -r public 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTFLoader } from 'three/addons/loaders/GLTFLoader.js';

export function Emblem3d(props) {
  const loader = new GLTFLoader();
  loader.load('./assets/emblem3d.gltf', (gltf) => {
  const {model} = gltf.scene;
  // Add the model to your scene or perform any other necessary operations.
})

  return (
    <group {...props} dispose={null} scale={30}>
      <mesh geometry={nodes.mesh_0.geometry} material={nodes.mesh_0.material} />
    </group>
  )
}

useGLTF.preload('/../src/assets/emblem3d.gltf')
